# Site settings
title: Jonathan Jonsson
email: jonsson.h.jonathan@gmail.com
url: jonathanjonsson.github.io
description: "Welcome! My name is Joanthan and I'm a game programmer"
keywords: "game, game developer, Jonathan, Jonsson, programming, developer"
skills: "Game programmer"
meta_author: Jonsson Jonathan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/JonathanJonsson
- title: linkedin
url: https://www.linkedin.com/in/jonathan-jonsson-50346a44

# Postal address (add as many lines as necessary)
address:
  - line: Stockholm

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
